# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PagedResponsePageableSort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sorted: bool=None, unsorted: bool=None):  # noqa: E501
        """PagedResponsePageableSort - a model defined in Swagger

        :param sorted: The sorted of this PagedResponsePageableSort.  # noqa: E501
        :type sorted: bool
        :param unsorted: The unsorted of this PagedResponsePageableSort.  # noqa: E501
        :type unsorted: bool
        """
        self.swagger_types = {
            'sorted': bool,
            'unsorted': bool
        }

        self.attribute_map = {
            'sorted': 'sorted',
            'unsorted': 'unsorted'
        }
        self._sorted = sorted
        self._unsorted = unsorted

    @classmethod
    def from_dict(cls, dikt) -> 'PagedResponsePageableSort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PagedResponse_pageable_sort of this PagedResponsePageableSort.  # noqa: E501
        :rtype: PagedResponsePageableSort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sorted(self) -> bool:
        """Gets the sorted of this PagedResponsePageableSort.


        :return: The sorted of this PagedResponsePageableSort.
        :rtype: bool
        """
        return self._sorted

    @sorted.setter
    def sorted(self, sorted: bool):
        """Sets the sorted of this PagedResponsePageableSort.


        :param sorted: The sorted of this PagedResponsePageableSort.
        :type sorted: bool
        """

        self._sorted = sorted

    @property
    def unsorted(self) -> bool:
        """Gets the unsorted of this PagedResponsePageableSort.


        :return: The unsorted of this PagedResponsePageableSort.
        :rtype: bool
        """
        return self._unsorted

    @unsorted.setter
    def unsorted(self, unsorted: bool):
        """Sets the unsorted of this PagedResponsePageableSort.


        :param unsorted: The unsorted of this PagedResponsePageableSort.
        :type unsorted: bool
        """

        self._unsorted = unsorted
