# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.paged_response_pageable_sort import PagedResponsePageableSort  # noqa: F401,E501
from swagger_server import util


class PagedResponsePageable(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sort: PagedResponsePageableSort=None, offset: int=None, page_number: int=None, page_size: int=None, paged: bool=None, unpaged: bool=None):  # noqa: E501
        """PagedResponsePageable - a model defined in Swagger

        :param sort: The sort of this PagedResponsePageable.  # noqa: E501
        :type sort: PagedResponsePageableSort
        :param offset: The offset of this PagedResponsePageable.  # noqa: E501
        :type offset: int
        :param page_number: The page_number of this PagedResponsePageable.  # noqa: E501
        :type page_number: int
        :param page_size: The page_size of this PagedResponsePageable.  # noqa: E501
        :type page_size: int
        :param paged: The paged of this PagedResponsePageable.  # noqa: E501
        :type paged: bool
        :param unpaged: The unpaged of this PagedResponsePageable.  # noqa: E501
        :type unpaged: bool
        """
        self.swagger_types = {
            'sort': PagedResponsePageableSort,
            'offset': int,
            'page_number': int,
            'page_size': int,
            'paged': bool,
            'unpaged': bool
        }

        self.attribute_map = {
            'sort': 'sort',
            'offset': 'offset',
            'page_number': 'pageNumber',
            'page_size': 'pageSize',
            'paged': 'paged',
            'unpaged': 'unpaged'
        }
        self._sort = sort
        self._offset = offset
        self._page_number = page_number
        self._page_size = page_size
        self._paged = paged
        self._unpaged = unpaged

    @classmethod
    def from_dict(cls, dikt) -> 'PagedResponsePageable':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PagedResponse_pageable of this PagedResponsePageable.  # noqa: E501
        :rtype: PagedResponsePageable
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sort(self) -> PagedResponsePageableSort:
        """Gets the sort of this PagedResponsePageable.


        :return: The sort of this PagedResponsePageable.
        :rtype: PagedResponsePageableSort
        """
        return self._sort

    @sort.setter
    def sort(self, sort: PagedResponsePageableSort):
        """Sets the sort of this PagedResponsePageable.


        :param sort: The sort of this PagedResponsePageable.
        :type sort: PagedResponsePageableSort
        """

        self._sort = sort

    @property
    def offset(self) -> int:
        """Gets the offset of this PagedResponsePageable.


        :return: The offset of this PagedResponsePageable.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this PagedResponsePageable.


        :param offset: The offset of this PagedResponsePageable.
        :type offset: int
        """

        self._offset = offset

    @property
    def page_number(self) -> int:
        """Gets the page_number of this PagedResponsePageable.


        :return: The page_number of this PagedResponsePageable.
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number: int):
        """Sets the page_number of this PagedResponsePageable.


        :param page_number: The page_number of this PagedResponsePageable.
        :type page_number: int
        """

        self._page_number = page_number

    @property
    def page_size(self) -> int:
        """Gets the page_size of this PagedResponsePageable.


        :return: The page_size of this PagedResponsePageable.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: int):
        """Sets the page_size of this PagedResponsePageable.


        :param page_size: The page_size of this PagedResponsePageable.
        :type page_size: int
        """

        self._page_size = page_size

    @property
    def paged(self) -> bool:
        """Gets the paged of this PagedResponsePageable.


        :return: The paged of this PagedResponsePageable.
        :rtype: bool
        """
        return self._paged

    @paged.setter
    def paged(self, paged: bool):
        """Sets the paged of this PagedResponsePageable.


        :param paged: The paged of this PagedResponsePageable.
        :type paged: bool
        """

        self._paged = paged

    @property
    def unpaged(self) -> bool:
        """Gets the unpaged of this PagedResponsePageable.


        :return: The unpaged of this PagedResponsePageable.
        :rtype: bool
        """
        return self._unpaged

    @unpaged.setter
    def unpaged(self, unpaged: bool):
        """Sets the unpaged of this PagedResponsePageable.


        :param unpaged: The unpaged of this PagedResponsePageable.
        :type unpaged: bool
        """

        self._unpaged = unpaged
